### ISSUE TITLE
InvalidRequestError: The model: `code-davinci-002` does not exist

### ISSUE THREAD

**Issue by Tony363** [cvlab-columbia/viper#11]
Hello,

I managed to confirm that the API key I have from openai can request the openai framework via this [openai test script .](https://github.com/openai/openai-python#usage) without RateLimitError. However, I was not able to get ViperGPT running on the jupytur notebook test example yet. 

I have compiled maskrcnn_benchmark on `| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4   `

It would keep running the `get_code` function for hours and when I interrupt the jupytur notebook, I would get the below error.

`InvalidRequestError: The model: code-davinci-002 does not exist
`
What might the issue be?

**Comment by Tony363** [comment]
[This](https://the-decoder.com/openai-kills-code-model-codex/ ) article says codex based models are no longer available?

**Comment by Tony363** [comment]
`['babbage', 'davinci', 'text-davinci-edit-001', 'babbage-code-search-code', 'text-similarity-babbage-001', 'code-davinci-edit-001', 'text-davinci-001', 'ada', 'babbage-code-search-text', 'babbage-similarity', 'code-search-babbage-text-001', 'text-curie-001', 'whisper-1', 'code-search-babbage-code-001', 'text-davinci-003', 'text-ada-001', 'text-embedding-ada-002', 'text-similarity-ada-001', 'curie-instruct-beta', 'ada-code-search-code', 'ada-similarity', 'code-search-ada-text-001', 'text-search-ada-query-001', 'davinci-search-document', 'ada-code-search-text', 'text-search-ada-doc-001', 'davinci-instruct-beta', 'text-similarity-curie-001', 'code-search-ada-code-001', 'ada-search-query', 'text-search-davinci-query-001', 'curie-search-query', 'davinci-search-query', 'babbage-search-document', 'ada-search-document', 'text-search-curie-query-001', 'text-search-babbage-doc-001', 'curie-search-document', 'text-search-curie-doc-001', 'babbage-search-query', 'text-babbage-001', 'text-search-davinci-doc-001', 'text-search-babbage-query-001', 'curie-similarity', 'gpt-3.5-turbo-0301', 'curie', 'gpt-3.5-turbo', 'text-similarity-davinci-001', 'text-davinci-002', 'davinci-similarity', 'cushman:2020-05-03', 'ada:2020-05-03', 'babbage:2020-05-03', 'curie:2020-05-03', 'davinci:2020-05-03', 'if-davinci-v2', 'if-curie-v2', 'if-davinci:3.0.0', 'davinci-if:3.0.0', 'davinci-instruct-beta:2.0.0', 'text-ada:001', 'text-davinci:001', 'text-curie:001', 'text-babbage:001']`

Maybe I can try some of the models above until it works?

**Comment by surisdi** [comment]
Hi,

Codex is unfortunately no longer available. There is a note on our README (Quickstart section) where we mention it, and we also propose potential alternatives. Specifically, you can try using the GPT3.5 Turbo and GPT4 alternatives. Note however that these are not free, and they can generate content that is not necessarily code. In order to use them, we suggest that you try the `chatapi.prompt` file.
