### ISSUE TITLE
Any plans to include the video API in chatapi.prompt?

### ISSUE THREAD

**Issue by devaansh100** [cvlab-columbia/viper#13]
I was hoping to run VideoQA using ViperGPT, however, since Codex was discontinued, the same was not possible with ChatGPT. Have you explored other API prompts for videos to work in the same context window?

**Comment by sachit-menon** [comment]
Sorry for not catching this -- we haven’t tried with video in the shorter context window, probably the best way would be to remove the image functions you don’t need and paste the VideoSegment class back in. (It does fit including the video parts for GPT-4 if you can get access to that.)
