### ISSUE TITLE
Not working on Apple Silicon

### ISSUE THREAD

**Issue by mberman84** [cvlab-columbia/viper#14]
I'm trying to get this working on my Mac M2. However, Decord doesn't seem to have a version for Apple Silicon. Alternatively, I've been trying to get it to work with Google Colab, but Conda + Colab has been difficult. Any suggestions for what to do?

**Comment by surisdi** [comment]
Hi,

`decord` is only used to load videos, so if you want to try ViperGPT on images, you can just comment out the lines that import `decord` ([this line](https://github.com/cvlab-columbia/viper/blob/d1d7f6f5902dd7cbc8e431755e36579cdc936a44/datasets/dataset.py#L3) and the next one).

If you want to load videos, you can replace the [`get_video`](https://github.com/cvlab-columbia/viper/blob/d1d7f6f5902dd7cbc8e431755e36579cdc936a44/datasets/dataset.py#L58) function with one that uses another library ([here](https://pytorch.org/vision/main/auto_examples/plot_video_api.html) are some alternatives).

We have not tried the code on macOS, so you may encounter other issues.
