### ISSUE TITLE
Appendix B, listings 2,3,4, and 5? 

### ISSUE THREAD

**Issue by rodrigob** [cvlab-columbia/viper#2]
I am looking for the API examples provided per-dataset as hinted in listings 2,3,4, and 5, of the appendix.
From a quick search I could not find them in the codebase. Are they available somewhere?

**Comment by surisdi** [comment]
Hi, thanks for your interest! We will release benchmark-specific details upon paper acceptance.

**Comment by rodrigob** [comment]
In the meantime:
a) Can you confirm that he prompt includes: the API (with docstring documentation) + dataset specific examples of how to use the API + the image & text question.
b) Could you indicate (roughly) how many dataset specific examples are provided in the prompt  ?

Thanks for your reply!

**Comment by surisdi** [comment]
Hi Rodrigo,

a) The prompt for the benchmarks includes the API + dataset-specific query-code example pairs, but it does *not* contain the image or video (Codex does not take visual input). It also does not contain the ground truth answer.

b) We use around 8 examples per dataset.

**Comment by surisdi** [comment]
Thanks for the suggestion! 
The use of examples is mentioned in Section 3 (not only at the end of the appendix), but we agree it could be clearer that dataset-specific optional examples can be included; we follow Flamingo (Appendix A2) [1] in primarily discussing this in the Appendix. 
We also want to point out that in the wild, these are not necessary — results like those in Figure 1 don’t use any examples.
