### ISSUE TITLE
Issues downloading models from Google Drive

### ISSUE THREAD

**Issue by apoorvkh** [cvlab-columbia/viper#21]
Hey, thanks for your great work!

I was just trying to download the pretrained models and encountered the following issues with `gdown`.

For example, this command:

```bash
gdown "https://drive.google.com/uc?id=1Cb1azBdcdbm0pRMFs-tupKxILTCXlB4O" -O $PRETRAINED_MODELS_PATH/TCL/TCL_4M.pth
```

results in:

```bash
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1Cb1azBdcdbm0pRMFs-tupKxILTCXlB4O
```

Of course, I downloaded the files manually instead. But it would be great if you can fix this. I had this issue for the X-VLM, TCL, and InSPyReNet models.

**Comment by surisdi** [comment]
We do not have any control over the `gdown` library. If you know of any other alternative to consistently download files from Google Drive, we will appreciate a pull request.

**Comment by apoorvkh** [comment]
I thought it was a permissions issue, but maybe not. Looks like this is an issue with gdown, so I'm not sure what the solution is.

https://github.com/wkentaro/gdown/issues/43

I tried upgrading gdown and using `--no-cookies`, but neither worked.

**Comment by surisdi** [comment]
Closing the issue because I do not know other ways of downloading Google Drive files, but feel free to re-open if you find a solution or have related problems.

**Comment by apoorvkh** [comment]
Hey, thanks for getting back to this. Fwiw:

For my project, I re-uploaded some of the model files to Huggingface: https://huggingface.co/apoorvkh/visual-question-decomposition/tree/main/viper

I have an automatic download script: https://github.com/brown-palm/visual-question-decomposition/blob/viper/viper/download_models/__main__.py
