### ISSUE TITLE
Consider removing HiddenPrints?

### ISSUE THREAD

**Issue by apoorvkh** [cvlab-columbia/viper#22]
I was trying to run your code (e.g. `from vision_processes import forward`), but the program would crash without my knowledge.

I believe the program crashed within a `HiddenPrints` context manager, in this case at:

https://github.com/cvlab-columbia/viper/blob/03ba31e4ec3553dddd1c772599b96afba1ab98d6/vision_models.py#L1223-L1224

But accordingly, this never invoked `HiddenPrints.__exit__`

https://github.com/cvlab-columbia/viper/blob/03ba31e4ec3553dddd1c772599b96afba1ab98d6/utils.py#L194

So I never discovered the issue and consequently nothing else in my program was able to print anything. I had no idea why and this was very difficult to debug.

Would you please consider removing HiddenPrints from this codebase? I think it is better to show extra warnings than to risk such "unknown crashes". Thanks!

**Comment by surisdi** [comment]
Hi, can you comment out the line [`with warnings.catch_warnings(), HiddenPrints("XVLM"):`](https://github.com/cvlab-columbia/viper/blob/03ba31e4ec3553dddd1c772599b96afba1ab98d6/vision_models.py#L1223)? What error do you get?

And I agree that `HiddenPrints` can make things hard to debug, so I will add a flag to make it optional.

**Comment by surisdi** [comment]
Update: I made HiddenPrints inactive by default

**Comment by apoorvkh** [comment]
Great, thank you!

No worries about my specific issue. That was local and I fixed it (after commenting out HiddenPrints). Just wanted to point out my experience with HiddenPrints.
