### ISSUE TITLE
Unable to download GLIP large checkpoint

### ISSUE THREAD

**Issue by sdebnathusc** [cvlab-columbia/viper#27]
Hi Team,

Thank you for your amazing work! 

I get the below error when trying to download GLIP large checkpoint using `wget -nc -P $PRETRAINED_MODELS_PATH/GLIP/checkpoints https://penzhanwu2bbs.blob.core.windows.net/data/GLIPv1_Open/models/glip_large_model.pth`

Error:

```
Resolving penzhanwu2bbs.blob.core.windows.net (penzhanwu2bbs.blob.core.windows.net)... 20.60.68.132
Connecting to penzhanwu2bbs.blob.core.windows.net (penzhanwu2bbs.blob.core.windows.net)|20.60.68.132|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2023-05-30 16:21:45 ERROR 409: Public access is not permitted on this storage account..
```

**Comment by sarvghotra** [comment]
You can download it from here: https://huggingface.co/GLIPModel/GLIP/blob/main/glip_large_model.pth
