### ISSUE TITLE
Minor issue: the link to the image in the notebook demo needs to be updated

### ISSUE THREAD

**Issue by Nineves** [cvlab-columbia/viper#36]
Not a big issue though :D. 
Furthermore, I think they moved most checkpoints of **GLIP** to huggingface. Here's the link (including both large and tiny versions):
https://huggingface.co/GLIPModel/GLIP/tree/main
It would be nicer if it could be included in the `Pretrained models`  of `readme`, since the link for downloading GLIP checkpoints in `download_models.sh` does not work anymore.

**Comment by surisdi** [comment]
Thanks! Updated.
