### ISSUE TITLE
API for VideoQA

### ISSUE THREAD

**Issue by Ziyang412** [cvlab-columbia/viper#38]
Hi, thanks for the great work! I really love this paper and really happy to try some VideoQA examples on this model. 

In this process, I faced some questions. It will be really nice of you to share any useful information with me!

1. The API in the paper and in the api.prompt file are slightly different, may I ask which is the final version? 

2. Also, I noticed https://github.com/cvlab-columbia/viper/blob/bde4c6343825e6a131547cdfdeed8a62c9ac4b11/prompts/api.prompt#L443, I am wondering whether you also add some in-context examples to the prompt, if so, may I know the exact number and the exact examples? Knowing this prompt will largely help me reproduce the results of the VideoQA task. 

Any help would be highly appreciated. Thanks in advance!

**Comment by surisdi** [comment]
Hi, we updated the code with the benchmark-specific prompts (including examples).
