### ISSUE TITLE
How to address problems with generated code

### ISSUE THREAD

**Issue by stevebottos** [cvlab-columbia/viper#4]
I've managed to bump up against an issue with the generated code:
![image](https://user-images.githubusercontent.com/32916895/226760771-28bc6ae9-b89b-4057-818d-066c7d2a6b09.png)
Any recommended ways around this?

**Comment by sachit-menon** [comment]
Hi, this is an issue with the visualization function. We'll try to put together a fix. In the meantime, the code should run if you set `show_intermediate_steps` to False.

**Comment by surisdi** [comment]
Hi, it should work now with the latest commit.
