### ISSUE TITLE
BLIP-2 Accelerate ImportError

### ISSUE THREAD

**Issue by Ziruiwang409** [cvlab-columbia/viper#42]
Thanks for the great work and the latest update on eval script. When I was trying to run the model, I meet the following problem when loading BLIP-2 model: 
![image](https://github.com/cvlab-columbia/viper/assets/73417516/e6622820-f0fe-4289-8978-da26baeb745c)

I m wondering how to solve this problem, thanks!

**Comment by surisdi** [comment]
Have you tried installing accelerate using `pip install accelerate` ?

**Comment by Ziruiwang409** [comment]
Yes, it's the version difference that causes the issue. Thanks
