### ISSUE TITLE
Missing function from OKVQA datasets

### ISSUE THREAD

**Issue by JaywonKoo17** [cvlab-columbia/viper#46]
The function all_answers_from_dict is missing in the datasets.py file. 
https://github.com/cvlab-columbia/viper/blob/b9221c29d3dac224fc4cb044607a656c2d868d99/datasets/okvqa.py#L14

Can you provide this function? 
Thanks in advance!

**Comment by surisdi** [comment]
Hi, I just added this function in the last commit. Thanks for the heads up.
